name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # # - run: echo ${{ secrets.DOCKER_USERNAME }}
      # # - run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # # - run: docker build -t cygnetops/react-test -f Dockerfile.dev .
      # # - run: docker run -e CI=true cygnetops/react-test npm test
      # - name: Build Docker Image
      #   run: docker build -t cygnetops/react-test -f Dockerfile.dev .

      # - name: Run Tests
      #   run: docker run -e CI=true cygnetops/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: elbs-demo
          environment_name: Elbs-demo-env
          existing_bucket_name: elasticbeanstalk-us-east-1-992382752962
          region: eu-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
